"""views and downloads table

Revision ID: 57e069e229b4
Revises: dc38f9b87062
Create Date: 2020-12-02 16:20:26.128468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e069e229b4'
down_revision = 'dc38f9b87062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('download_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['download_id'], ['user.id'], )
    )
    op.create_table('views',
    sa.Column('view_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['view_id'], ['user.id'], )
    )
    op.drop_table('vc_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vc_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('hour', sa.INTEGER(), nullable=False),
    sa.Column('minute', sa.INTEGER(), nullable=False),
    sa.Column('ip', sa.VARCHAR(), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('args', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('views')
    op.drop_table('downloads')
    # ### end Alembic commands ###
