"""new fields

Revision ID: 5950d82d6041
Revises: 57e069e229b4
Create Date: 2020-12-04 17:28:48.648070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5950d82d6041'
down_revision = '57e069e229b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('viewed_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['viewed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('viewed_id', 'viewer_id')
    )
    op.drop_table('downloads')
    op.drop_table('views')
    op.add_column('user', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'views')
    op.create_table('views',
    sa.Column('view_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['view_id'], ['user.id'], )
    )
    op.create_table('downloads',
    sa.Column('download_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['download_id'], ['user.id'], )
    )
    op.drop_table('users')
    # ### end Alembic commands ###
