"""empty message

Revision ID: 9cf384f71fcb
Revises: 74597e9704d4
Create Date: 2020-12-10 17:20:44.356927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf384f71fcb'
down_revision = '74597e9704d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewers')
    op.drop_table('downloaders')
    op.alter_column('user', 'downloads',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'downloads',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('downloaders',
    sa.Column('downloaded_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['downloaded_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('downloaded_id')
    )
    op.create_table('viewers',
    sa.Column('viewed_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['viewed_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('viewed_id')
    )
    # ### end Alembic commands ###
