"""download variable

Revision ID: d3ff47349913
Revises: 5950d82d6041
Create Date: 2020-12-07 14:59:44.198619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ff47349913'
down_revision = '5950d82d6041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('user', sa.Column('downloads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'downloads')
    op.create_table('users',
    sa.Column('viewed_id', sa.INTEGER(), nullable=False),
    sa.Column('viewer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['viewed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('viewed_id', 'viewer_id')
    )
    # ### end Alembic commands ###
